[GENERAL]
INSTRUMENT      = CORAL
STATION_NAME    = Rio Grande, Argentina
RESOLUTION      = *T15Z900.nc
RESOLUTION_BG   = *T120Z900.nc
RESOLUTION_AEROSOL = *T2Z100.nc
RESOLUTION_NLC = *T10Z100.nc
TIMEFRAME_NIGHT = [17,13]
#TIMEFRAME_NIGHT = [19,13]
TRANGE_PROF     = [150,350]
TRANGE          = [150,300]
BSRRANGE	= [1,5]
ALTITUDE_RANGE  = [11,94]
ALTITUDE_RANGE_AEROSOL  = [8,50]
ALTITUDE_RANGE_NLC  = [78,90]
OVERVIEW_RANGE  = ['2020-01', '2020-07']

[INPUT]
OBS_FOLDER      = /export/data2/malidar/tana/Southwave/v18combined
#OBS_FOLDER      = /athome/f_malid/test/tana/comb
AEROSOL_FOLDER  = /export/data2/malidar/aerosol/Southwave/v2
OBS_FILE        = NONE

[OUTPUT]
FOLDER          = ../data/coral
OVERVIEW_FILE   = coral_overview.png

[ERA5]
AREA            = -38/255/-70.5/315
#AREA           = -37.5/-105/-72.5/-45
#AREA           = -25/-120/-85/-30
AREA_PROFILE    = -53/292/-54/293
WESTERN_COORDS  = True
LAT             = -53.75
# LON           = 292.25
LON             = -67.75
LAT_AVG         = [-52.5,-57.5]
LON_AVG         = [290,295]
LON_RANGE       = [-105,-45]
LAT_RANGE       = [-70.5,-38]

[NOTES]
# AREA: North/West/South/East. Default: global
# AREA 
# bwf15, bwf20, tm (temporal mean), rm (running mean)
# 19:00--13:00 -> 4UTC (1am local) in center
