[GENERAL]
INSTRUMENT      = CORAL
STATION_NAME    = Sodankyla, Finland
RESOLUTION      = *T15Z900.nc
RESOLUTION_BG   = *T120Z900.nc
RESOLUTION_AEROSOL = *T2Z100.nc
TIMEFRAME_NIGHT = NONE
#TIMEFRAME_NIGHT = [19,13]
TRANGE_PROF     = [150,350]
TRANGE          = [150,300]
BSRRANGE	= [1,5]
ALTITUDE_RANGE  = [11,94]
ALTITUDE_RANGE_AEROSOL  = [8,30]
OVERVIEW_RANGE  = ['2014-06', '2014-12']

[INPUT]
OBS_FOLDER      = /export/data2/malidar/tana/Northwave/v21combined
AEROSOL_FOLDER  = /export/data2/malidar/tana/Northwave
OBS_FILE        = NONE

[OUTPUT]
FOLDER          = ../data/coral
OVERVIEW_FILE   = northwave_overview.png

[ERA5]
AREA            = -20/100/-60/220
AREA_PROFILE    = -45/169/-46/170
WESTERN_COORDS  = True
LAT             = -45.04
LON             = 169.68
LAT_AVG         = [-42.5,-47.5]
LAT_RANGE       = [-60,-20]
LON_AVG         = [167.5,172.5]
LON_RANGE       = [100,220]

[NOTES]
# AREA: North/West/South/East. Default: global
# AREA 
# bwf15, bwf20, tm (temporal mean), rm (running mean)
# 19:00--13:00 -> 4UTC (1am local) in center
