[GENERAL]
INSTRUMENT      = ERL
STATION_NAME    = DLR Oberpfaffenhofen
RESOLUTION      = *T20Z900.nc
RESOLUTION_BG   = *T120Z900.nc
RESOLUTION_AEROSOL = *T2Z100.nc
TIMEFRAME_NIGHT = [18,5]
TRANGE_PROF     = [150,350]
TRANGE          = [150,300]
BSRRANGE	= [1,5]
ALTITUDE_RANGE  = [11,94]
ALTITUDE_RANGE_AEROSOL  = [8,30]
OVERVIEW_RANGE  = ['2024-01', '2024-12']

[INPUT]
OBS_FOLDER      = /export/data2/malidar/tana/OP/v1
AEROSOL_FOLDER  = /export/data2/malidar/tana/OP/v1
OBS_FILE        = NONE

[OUTPUT]
FOLDER          = ../data/OP
OVERVIEW_FILE   = OP_overview.png

[ERA5]
AREA            = 30/0/60/100
AREA_PROFILE    = 48/11/-49/12
WESTERN_COORDS  = True
LAT             = 48
LON             = 11
LAT_AVG         = [47,49]
LAT_RANGE       = [38,58]
LON_AVG         = [11,12]
LON_RANGE       = [0,100]

[NOTES]
# AREA: North/West/South/East. Default: global
# AREA 
# bwf15, bwf20, tm (temporal mean), rm (running mean)
# 19:00--13:00 -> 4UTC (1am local) in center
